# Generated by Django 5.1.2 on 2024-10-15 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transactiontypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='trans/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('types', models.CharField(choices=[('SA', 'SAVING ACCOUNT'), ('CA', 'CURRENT ACCOUNT'), ('LA', 'LOAN ACCOUNT')], max_length=2)),
            ],
        ),
    ]
